#!/bin/bash

date1=$(date +"%s")
rm -rf build Resources
ti build --platform android -T device --force
date2=$(date +"%s")
diff=$(($date2-$date1))
echo "$(($diff / 60)) minutes and $(($diff % 60)) seconds elapsed."
